#!/usr/bin/env python3
"""
Fix all internal links in markdown files to use absolute paths starting with /rag/
This ensures all links work correctly with Jekyll's baseurl.
"""

import re
from pathlib import Path
import sys

RAG_DIR = Path("rag")

def fix_links_in_file(file_path: Path):
    """Fix all internal links in a markdown file to use absolute paths."""
    try:
        content = file_path.read_text(encoding='utf-8')
    except Exception as e:
        print(f"Warning: Could not read {file_path}: {e}", file=sys.stderr)
        return False
    
    # Get relative path from rag/ directory
    try:
        rel_path = file_path.relative_to(RAG_DIR)
    except ValueError:
        return False
    
    # Get the directory containing this file (relative to rag/)
    file_dir = rel_path.parent
    
    modified = False
    new_content = content
    
    # Pattern to match markdown links: [text](url)
    link_pattern = r'\[([^\]]+)\]\(([^\)]+)\)'
    
    def replace_link(match):
        nonlocal modified
        link_text = match.group(1)
        link_url = match.group(2)
        
        # Skip external links
        if link_url.startswith(("http://", "https://", "mailto:")):
            return match.group(0)
        
        # Skip anchor links
        if link_url.startswith("#"):
            return match.group(0)
        
        # Skip Jekyll template syntax
        if "{{" in link_url or "|" in link_url:
            return match.group(0)
        
        # Skip if already absolute path starting with /rag/
        if link_url.startswith("/rag/"):
            return match.group(0)
        
        # Convert relative path to absolute path
        if link_url.endswith(".html") or link_url.endswith(".md"):
            # Resolve relative path
            if file_dir == Path("."):
                # File is in rag/ root
                new_url = f"/rag/{link_url}"
            else:
                # File is in a subdirectory
                resolved = (file_dir / link_url).resolve()
                try:
                    rel_to_rag = resolved.relative_to(RAG_DIR.resolve())
                    rel_str = str(rel_to_rag).replace('\\', '/')
                    new_url = f"/rag/{rel_str}"
                except ValueError:
                    # Link points outside rag/ directory, keep as is
                    return match.group(0)
            
            # Convert .md to .html if needed
            if new_url.endswith(".md"):
                new_url = new_url[:-3] + ".html"
            
            modified = True
            return f"[{link_text}]({new_url})"
        
        return match.group(0)
    
    # Replace all links
    new_content = re.sub(link_pattern, replace_link, content)
    
    if modified:
        file_path.write_text(new_content, encoding='utf-8')
        print(f"Fixed links in: {file_path}")
        return True
    
    return False

def main():
    """Fix all links in all markdown files."""
    if not RAG_DIR.exists():
        print(f"Error: {RAG_DIR} directory not found", file=sys.stderr)
        sys.exit(1)
    
    fixed_count = 0
    total_files = 0
    
    for file_path in RAG_DIR.rglob("*.md"):
        # Skip rag-index.md (it's generated by sync-homepage.py)
        if file_path.name == "rag-index.md":
            continue
        
        total_files += 1
        if fix_links_in_file(file_path):
            fixed_count += 1
    
    print(f"\n✅ Fixed links in {fixed_count} out of {total_files} files")

if __name__ == "__main__":
    main()

