#!/usr/bin/env python3
"""
Fix incorrect link paths that were generated by fix-all-links.py.
Some paths have duplicate directories or incorrect parent directory resolution.
"""

import re
from pathlib import Path
import sys

RAG_DIR = Path("rag")

# Patterns to fix
FIXES = [
    # Duplicate directories: /rag/adoption/adoption/ -> /rag/adoption/
    (r'/rag/([^/]+)/\1/', r'/rag/\1/'),
    # Wrong paths from adoption directory
    (r'/rag/adoption/observability/', r'/rag/observability/'),
    (r'/rag/adoption/development/', r'/rag/development/'),
    (r'/rag/adoption/project-methods/', r'/rag/project-methods/'),
    (r'/rag/adoption/security/', r'/rag/security/'),
    (r'/rag/adoption/testing/', r'/rag/testing/'),
    (r'/rag/adoption/troubleshooting/', r'/rag/troubleshooting/'),
    (r'/rag/adoption/integrations/', r'/rag/integrations/'),
    (r'/rag/adoption/data-modeling/', r'/rag/data-modeling/'),
    (r'/rag/adoption/data-governance/', r'/rag/data-governance/'),
    # Add more patterns as needed
]

def fix_file(file_path: Path):
    """Fix incorrect paths in a file."""
    try:
        content = file_path.read_text(encoding='utf-8')
    except Exception as e:
        print(f"Warning: Could not read {file_path}: {e}", file=sys.stderr)
        return False
    
    modified = False
    new_content = content
    
    for pattern, replacement in FIXES:
        if re.search(pattern, new_content):
            new_content = re.sub(pattern, replacement, new_content)
            modified = True
    
    if modified:
        file_path.write_text(new_content, encoding='utf-8')
        print(f"Fixed paths in: {file_path}")
        return True
    
    return False

def main():
    """Fix all incorrect paths."""
    if not RAG_DIR.exists():
        print(f"Error: {RAG_DIR} directory not found", file=sys.stderr)
        sys.exit(1)
    
    fixed_count = 0
    total_files = 0
    
    for file_path in RAG_DIR.rglob("*.md"):
        # Skip rag-index.md (it's generated)
        if file_path.name == "rag-index.md":
            continue
        
        total_files += 1
        if fix_file(file_path):
            fixed_count += 1
    
    print(f"\n✅ Fixed paths in {fixed_count} out of {total_files} files")

if __name__ == "__main__":
    main()

