source "https://rubygems.org"

# Jekyll
gem "jekyll", "~> 4.3"

# Jekyll plugins (compatible with Jekyll 4.x)
gem "jekyll-feed", "~> 0.15"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-seo-tag", "~> 2.8"

# Ruby version
ruby "~> 3.1"

