source "https://rubygems.org"

# Jekyll and GitHub Pages
gem "jekyll", "~> 4.3"
gem "github-pages", group: :jekyll_plugins

# Jekyll plugins
gem "jekyll-feed", "~> 0.15"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-seo-tag", "~> 2.8"

# Ruby version
ruby "~> 3.1"

